homework_09 complete
NikitaKuzminn/NikitaKuzmin pull request #10
Opened 2021-12-02 08:21 UTC by NikitaKuzminn

2021-12-03 11:25 UTC, kristinaChander commented on src/main/java/home/epam/hw9/entities/BoardDto.java
> +@Setter
Why don't you use @Data

2021-12-03 11:26 UTC, kristinaChander commented on src/main/java/home/epam/hw9/entities/BoardDto.java
> +    @SerializedName("id")
What does this annotation do? Do you need it?

2021-12-03 11:26 UTC, kristinaChander commented on src/main/java/home/epam/hw9/entities/BoardDto.java
> +    @Expose
What does this annotation do? Do you need it?

2021-12-03 11:26 UTC, kristinaChander commented on src/main/java/home/epam/hw9/entities/ListDto.java
> +@Setter
@Data?

2021-12-03 11:26 UTC, kristinaChander commented on src/main/java/home/epam/hw9/entities/ListDto.java
> +    @Expose
Annotations?

2021-12-03 11:28 UTC, kristinaChander commented on src/main/java/home/epam/hw9/service/BoardService.java
> +    public static class BoardApiBuilder {
Naming convention - class name should be like "BoardServiceBuilder"

2021-12-03 11:35 UTC, kristinaChander commented on src/main/java/home/epam/hw9/service/CommonService.java
> +            .given(request).log().all()
do you need all the logs?

2021-12-03 11:35 UTC, kristinaChander commented on src/main/java/home/epam/hw9/service/CommonService.java
> +    public static RequestSpecification requestSpec(URI url) {
emove static - don't use static for inheritance

2021-12-03 11:37 UTC, kristinaChander commented on src/main/java/home/epam/hw9/service/ListService.java
> +    public static class ListApiBuilder {
change name

2021-12-03 11:38 UTC, kristinaChander commented on src/main/java/home/epam/hw9/util/ConfProperty.java
> +            properties = property.getProperty(name);
Shall we close the stream?

2021-12-03 11:39 UTC, kristinaChander commented on src/main/java/home/epam/hw9/util/Values.java
> +    public static final String USER_KEY = getProperty("key");
you read from file every time you invoke getProperty() method, can you read once and then use the already read info?

2021-12-03 11:40 UTC, kristinaChander commented on src/test/java/home/epam/hw9/data/DataProviders.java
> +    @DataProvider
you only use name, you don't need a DTO in your requests

2021-12-03 11:40 UTC, kristinaChander commented on src/test/java/home/epam/hw9/data/DataProviders.java
> +    public static Object[][] listData() {
you only use name, you don't need a DTO in your requests

2021-12-03 11:40 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +    public Response sendRequestAndGetResponse(BoardService.BoardApiBuilder api, ResponseSpecification resp) {
change method name

2021-12-03 11:41 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +        BoardService.BoardApiBuilder api = apiBoardBuilder()
change the variable name - it's a request - the name should reflect the main idea

2021-12-03 11:42 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +        Response response = api
change the variable name - it's a request - the name should reflect the main idea

2021-12-03 11:42 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +    public String createNewBoard(BoardDto boardDto) {
you don't need DTO - only name

2021-12-03 11:42 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +        BoardService.BoardApiBuilder api = apiBoardBuilder()
variable name

2021-12-03 11:42 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +    public void deleteBoard(String boardId) {
variable name

2021-12-03 11:43 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +        BoardService.BoardApiBuilder api = apiBoardBuilder()
variable name

2021-12-03 11:43 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/ListSteps.java
> +    public ListDto sendRequestAndGetResponse(ListService.ListApiBuilder api, ResponseSpecification resp) {
change method name

2021-12-03 11:43 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/ListSteps.java
> +        Response response = api
variable name

2021-12-03 11:44 UTC, kristinaChander commented on src/test/java/home/epam/hw9/steps/ListSteps.java
> +    public String createList(String boardId, ListDto listDto) {
you don't need dto

2021-12-03 11:44 UTC, kristinaChander commented on src/test/java/home/epam/hw9/tests/BoardDtoTest.java
> +    public void createBoardTest(BoardDto boardDto) {
you don't need DTO - only name

2021-12-03 11:44 UTC, kristinaChander commented on src/test/java/home/epam/hw9/tests/BoardDtoTest.java
> +    @Test(dataProvider = "boardData", dataProviderClass = DataProviders.class)
you don't need DTO - only name

2021-12-03 11:44 UTC, kristinaChander commented on src/test/java/home/epam/hw9/tests/BoardDtoTest.java
> +    @Test(dataProvider = "boardData", dataProviderClass = DataProviders.class)
you don't need DTO - only name

2021-12-03 11:45 UTC, kristinaChander commented on src/test/java/home/epam/hw9/tests/ListDtoTest.java
> +    @Test(dataProvider = "listData", dataProviderClass = DataProviders.class)
you don't need DTO - only name

2021-12-03 11:45 UTC, kristinaChander commented on src/test/java/home/epam/hw9/tests/ListDtoTest.java
> +    public void modifyListTest(BoardDto boardDto, ListDto listDto) {
you don't need DTO - only name

2021-12-03 11:45 UTC, kristinaChander commented on src/test/java/home/epam/hw9/tests/ListDtoTest.java
> +        listSteps = new ListSteps();
code duplication

2021-12-03 11:46 UTC, kristinaChander commented on src/test/java/home/epam/hw9/tests/ListDtoTest.java
> +        listSteps = new ListSteps();
code duplication listSteps = new ListSteps();

2021-12-03 11:47 UTC, kristinaChander requested changes
Please, resolve the comments

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/entities/BoardDto.java
> +@Setter
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/entities/BoardDto.java
> +    @SerializedName("id")
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/entities/BoardDto.java
> +    @Expose
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/entities/ListDto.java
> +@Setter
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/entities/ListDto.java
> +    @Expose
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/service/BoardService.java
> +    public static class BoardApiBuilder {
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/service/CommonService.java
> +            .given(request).log().all()
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/service/CommonService.java
> +    public static RequestSpecification requestSpec(URI url) {
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/service/ListService.java
> +    public static class ListApiBuilder {
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/util/ConfProperty.java
> +            properties = property.getProperty(name);
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/data/DataProviders.java
> +    @DataProvider
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/data/DataProviders.java
> +    public static Object[][] listData() {
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +        BoardService.BoardApiBuilder api = apiBoardBuilder()
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +        Response response = api
fixed

2021-12-03 17:28 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +    public String createNewBoard(BoardDto boardDto) {
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +        BoardService.BoardApiBuilder api = apiBoardBuilder()
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +    public void deleteBoard(String boardId) {
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +        BoardService.BoardApiBuilder api = apiBoardBuilder()
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/ListSteps.java
> +        Response response = api
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/ListSteps.java
> +    public String createList(String boardId, ListDto listDto) {
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/tests/BoardDtoTest.java
> +    public void createBoardTest(BoardDto boardDto) {
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/tests/BoardDtoTest.java
> +    @Test(dataProvider = "boardData", dataProviderClass = DataProviders.class)
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/tests/BoardDtoTest.java
> +    @Test(dataProvider = "boardData", dataProviderClass = DataProviders.class)
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/tests/ListDtoTest.java
> +    @Test(dataProvider = "listData", dataProviderClass = DataProviders.class)
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/tests/ListDtoTest.java
> +    public void modifyListTest(BoardDto boardDto, ListDto listDto) {
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/tests/ListDtoTest.java
> +        listSteps = new ListSteps();
fixed

2021-12-03 17:29 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/tests/ListDtoTest.java
> +        listSteps = new ListSteps();
fixed

2021-12-03 18:11 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/BoardSteps.java
> +    public Response sendRequestAndGetResponse(BoardService.BoardApiBuilder api, ResponseSpecification resp) {
fixed

2021-12-04 17:13 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw9/steps/ListSteps.java
> +    public ListDto sendRequestAndGetResponse(ListService.ListApiBuilder api, ResponseSpecification resp) {
fixed

2021-12-04 18:17 UTC, NikitaKuzminn commented on src/main/java/home/epam/hw9/util/Values.java
> +    public static final String USER_KEY = getProperty("key");
fixed

2021-12-07 12:20 UTC, merged