Homework 7 jdi
NikitaKuzminn/NikitaKuzmin pull request #8
Opened 2021-11-16 11:32 UTC by NikitaKuzminn

2021-11-26 11:14 UTC, troe88 requested changes

2021-11-26 11:14 UTC, troe88 commented on src/test/java/home/epam/hw7/site/JdiTestSite.java
> +    public static void shouldBeLoggedOut(AbstractPage page) {
What is the reason of AbstractPage as arg here?
It will be quite easier to logOut from HomePage, the same approach like _loginAsDefaultUser_

2021-11-26 11:14 UTC, troe88 commented on src/test/java/home/epam/hw7/site/components/Header.java
> +    @UI("ul.uui-navigation.nav.navbar-nav.m-l8 li a")
This locator can be simplified

2021-11-26 11:14 UTC, troe88 commented on src/test/java/home/epam/hw7/site/components/forms/MetalsAndColorsForm.java
> +public class MetalsAndColorsForm extends Section {
This class shoud be extended from Form<> class, the same way like LoginForm.

2021-11-26 11:14 UTC, troe88 commented on src/test/java/home/epam/hw7/tests/MetalsAndColorsPageTest.java
> +        homePage.isUserLoggedIn(User.DEFAULT_USER);
You have 2 different methods _loginAsDefaultUser_ and _isUserLoggedIn(User.DEFAULT_USER)_,
but this method should be created in similar way: 
1. with User as argument in both cases;
2. with defaul user as method's name with no argument.

2021-11-26 18:52 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw7/entities/MetalsAndColorsData.java
> +public class MetalsAndColorsData extends DataClass<MetalsAndColorsData> {
fixed

2021-11-26 19:00 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw7/site/components/Header.java
> +    @UI("ul.uui-navigation.nav.navbar-nav.m-l8 li a")
fixed

2021-11-26 19:09 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw7/site/JdiTestSite.java
> +    public static void shouldBeLoggedOut(AbstractPage page) {
fixed

2021-11-26 19:13 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw7/site/components/forms/MetalsAndColorsForm.java
> +public class MetalsAndColorsForm extends Section {
fixed

2021-11-26 19:20 UTC, NikitaKuzminn commented on src/test/java/home/epam/hw7/tests/MetalsAndColorsPageTest.java
> +        homePage.isUserLoggedIn(User.DEFAULT_USER);
fixed

2021-11-29 09:09 UTC, troe88 approved these changes

2021-11-29 09:11 UTC, merged